// app/src/views/browse/selected-set/MainSelectedSet.vue
<!--
 Copyright 2023 Open Reaction Database Project Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script>
import LoadingSpinner from '@/components/LoadingSpinner';
import reaction_pb from 'ord-schema';
import base64ToBytes from '@/utils/base64';
import ReactionCard from '@/components/ReactionCard';
import DownloadResults from '@/components/DownloadResults';
import CopyButton from '@/components/CopyButton';

export default {
  components: {
    LoadingSpinner,
    ReactionCard,
    DownloadResults,
    CopyButton,
  },
  data() {
    return {
      reactions: [],
      loading: true,
      showDownloadResults: false,
    };
  },
  computed: {
    reactionIds() {
      return [this.$route.query.reaction_id] || [];
    },
    fullUrl() {
      return window.location.href;
    },
  },
  methods: {
    async getSelectedReactions() {
      this.loading = true;
      try {
        const xhr = new XMLHttpRequest();
        xhr.open('POST', `/api/reactions`);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onload = () => {
          // if response is good, deserialize reaction and return object from protobuff
          let fetchedReactions = null;
          if (xhr.response !== null) {
            fetchedReactions = JSON.parse(xhr.response);
            fetchedReactions.forEach(reaction => {
              const base64string = reaction.proto;
              const bytes = base64ToBytes(base64string);
              reaction.data = reaction_pb.Reaction.deserializeBinary(bytes).toObject();
            });
          }
          this.reactions = fetchedReactions;
          this.loading = false;
        };
        xhr.send(JSON.stringify({ reaction_ids: this.reactionIds }));
      } catch (e) {
        console.log(e);
        this.loading = false;
      }
    },
  },
  mounted() {
    this.getSelectedReactions();
  },
};
</script>

<template lang="pug">
#selected-set-main
  .header
    .title Reaction Set
    .action-button-holder
      CopyButton(
        :textToCopy='fullUrl'
        icon='share'
        buttonText='Shareable Link'
      )
      button(
        :disabled='!reactionIds.length'
        @click='showDownloadResults=true'
      ) Download Reaction Set
  .selected-set(v-if='!loading && reactions.length')
    ReactionCard(
      v-for='reaction in reactions'
      :reaction='reaction'
      :isSelectable='false'
      :isSelected='false'
    )
  .no-results(v-else-if='!loading && !reactions?.length')
    .title There was an issue fetching your selected reactions.
  .loading(v-else)
    LoadingSpinner
  DownloadResults(
    :reactionIds='reactionIds'
    :showDownloadResults='showDownloadResults'
    @hideDownloadResults='showDownloadResults=false'
  )
</template>

<style lang="sass" scoped>
@import '@/styles/vars.sass'
#selected-set-main
  padding: 2rem
  .header
    display: grid
    grid-template-columns: 1fr auto
    margin-bottom: 1rem
    .title
      font-size: 2rem
      font-weight: 700
    .action-button-holder
      display: flex
      align-items: end
      column-gap: 0.5rem
</style>

// app/src/views/browse/selected-set/MainSelectedSet.tsx
/**
 * Copyright 2023 Open Reaction Database Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import reaction_pb from 'ord-schema';
import LoadingSpinner from '../../../components/LoadingSpinner';
import ReactionCard from '../../../components/ReactionCard';
import DownloadResults from '../../../components/DownloadResults';
import CopyButton from '../../../components/CopyButton';
import { base64ToBytes } from '../../../utils/base64';
import { fetchJson } from '../../../utils/api';
import type { SearchResult } from '../../../types/search';
import './MainSelectedSet.scss';

const MainSelectedSet: React.FC = () => {
  const [searchParams] = useSearchParams();
  const [reactions, setReactions] = useState<SearchResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [showDownloadResults, setShowDownloadResults] = useState(false);

  const reactionIds = useMemo(() => searchParams.getAll('reaction_id'), [searchParams]);
  const reactionIdsKey = reactionIds.join(',');
  const fullUrl = window.location.href;

  const getSelectedReactions = useCallback(async () => {
    setLoading(true);
    try {
      const fetched = await fetchJson<Array<Omit<SearchResult, 'data'>>>(
        '/api/reactions',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ reaction_ids: reactionIds }),
        },
        'reactions',
      );

      const decoded: SearchResult[] = fetched.map(r => ({
        ...r,
        data: reaction_pb.Reaction.deserializeBinary(
          new Uint8Array(base64ToBytes(r.proto)),
        ).toObject(),
      }));

      setReactions(decoded);
    } catch (error) {
      console.error('Error fetching reactions:', error);
      setReactions([]);
    } finally {
      setLoading(false);
    }
  }, [reactionIdsKey]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (reactionIds.length > 0) {
      getSelectedReactions();
    } else {
      setLoading(false);
    }
  }, [reactionIdsKey, getSelectedReactions]); // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) {
    return (
      <div id="selected-set-main">
        <div className="loading">
          <LoadingSpinner />
        </div>
      </div>
    );
  }

  if (!reactions.length) {
    return (
      <div id="selected-set-main">
        <div className="header">
          <div className="title">Reaction Set</div>
        </div>
        <div className="no-results">
          <div className="title">
            There was an issue fetching your selected reactions.
          </div>
        </div>
      </div>
    );
  }

  return (
    <div id="selected-set-main">
      <div className="header">
        <div className="title">Reaction Set</div>
        <div className="action-button-holder">
          <CopyButton
            textToCopy={fullUrl}
            icon="share"
            buttonText="Shareable Link"
          />
          <button
            disabled={!reactionIds.length}
            onClick={() => setShowDownloadResults(true)}
          >
            Download Reaction Set
          </button>
        </div>
      </div>

      <div className="selected-set">
        {reactions.map(reaction => (
          <ReactionCard
            key={reaction.reaction_id}
            reaction={reaction}
            isSelectable={false}
            isSelected={false}
          />
        ))}
      </div>

      <DownloadResults
        reactionIds={reactionIds}
        showDownloadResults={showDownloadResults}
        onHideDownloadResults={() => setShowDownloadResults(false)}
      />
    </div>
  );
};

export default MainSelectedSet;
