// app/src/components/ReactionCard.vue
<!--
 Copyright 2023 Open Reaction Database Project Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script>
import LoadingSpinner from '@/components/LoadingSpinner.vue';
import conditionUtil from '@/utils/conditions';
import outcomesUtil from '@/utils/outcomes';
import reaction_pb from 'ord-schema';
import CopyButton from '@/components/CopyButton.vue';

export default {
  props: {
    reaction: Object,
    isSelected: Boolean,
    isSelectable: Boolean,
  },
  components: {
    LoadingSpinner,
    CopyButton,
  },
  data() {
    return {
      formattedResults: [],
      selectedReactions: [],
      reactionTable: null,
    };
  },
  methods: {
    getReactionTable() {
      fetch(`/api/reaction_summary?reaction_id=${this.reaction.reaction_id}`)
        .then(response => response.text())
        .then(responseData => {
          this.reactionTable = responseData;
        });
    },
    getYield(measurements) {
      const yieldObj = measurements.find(m => m.type == 3); // ord-schema type 3 == "YIELD"
      if (yieldObj?.percentage) {
        return `${yieldObj.percentage.value}%`;
      } else {
        return 'Not listed';
      }
    },
    getConversion(reaction) {
      if (!reaction.outcomesList[0].conversion) return 'Not listed';
      // decode conversion
    },
    conditionsAndDuration(reaction) {
      const details = [];
      // get temp
      const tempSetPoint = conditionUtil.tempSetPoint(reaction.conditions.temperature?.setpoint);
      if (tempSetPoint !== 'None') details.push(`at ${tempSetPoint}`);

      // get Pressure
      const pressureSetPoint = conditionUtil.pressureSetPoint(reaction.conditions.pressure?.setpoint);
      if (pressureSetPoint !== 'None') details.push(`under ${pressureSetPoint}`);

      // get duration
      const formattedTime = outcomesUtil.formattedTime(reaction.outcomesList[0].reactionTime);
      if (formattedTime) details.push(`for ${formattedTime}`);

      return details;
    },
    productIdentifier(identifier) {
      const identifierTypes = reaction_pb.CompoundIdentifier.CompoundIdentifierType;
      const identifierType = Object.keys(identifierTypes).find(key => identifierTypes[key] == identifier.type);
      return `${identifierType}: ${identifier.value}`;
    },
    updateSelectedReactions(event) {
      if (event.target.checked) {
        this.selectedReactions.push(event.target.value);
      } else {
        let idx = this.selectedReactions.indexOf(event.target.value);
        if (idx !== -1) {
          this.selectedReactions.splice(idx, 1);
        }
      }
    },
  },
  async mounted() {
    this.getReactionTable();
  },
};
</script>

<template lang="pug">
.reaction-container
  .row(:class='isSelected ? "selected" : ""')
    .select(v-if='isSelectable')
      input(
        type="checkbox"
        :id='"select_"+reaction.reaction_id'
        :value='reaction.reaction_id'
        :checked='isSelected'
        @change='$emit("clickedSelect", $event)'
      )
      label(:for='"select_"+reaction.reaction_id') Select reaction
    .is-mined(v-if='reaction.data.provenance.isMined')
      .is-mined-badge Mined
    .reaction-table(
      v-html='reactionTable'
      v-if='reactionTable'
    )
    LoadingSpinner(v-else)
    .info
      .col.full
        router-link(
          :to='{ name: "reaction-view", params: {reactionId: reaction.reaction_id}}'
        ) 
          button View Full Details
      .col
        .yield Yield: {{getYield(reaction.data.outcomesList[0].productsList[0].measurementsList)}}
        .conversion Conversion: {{getConversion(reaction.data)}}
        .conditions Conditions: {{conditionsAndDuration(reaction.data).join("; ") || "Not Listed"}}
        .smile(v-if='reaction.data.outcomesList[0].productsList[0].identifiersList.length')
          CopyButton(
            :textToCopy='reaction.data.outcomesList[0].productsList[0].identifiersList[0].value'
          )
          .value Product {{productIdentifier(reaction.data.outcomesList[0].productsList[0].identifiersList[0])}}
      .col
        .creator Uploaded by {{reaction.data.provenance.recordCreated.person.name}}, {{reaction.data.provenance.recordCreated.person.organization}}
        .date Uploaded on {{new Date(reaction.data.provenance.recordCreated.time.value).toLocaleDateString()}}
        .doi DOI: {{reaction.data.provenance.doi}}
        .publication 
          a(
            :href='reaction.data.provenance.publicationUrl'
            target="_blank"
          ) Publication URL
        .dataset Dataset: 
          a(
            :href='"/search?dataset_id=" + reaction.dataset_id + "&limit=100"'
            target="_blank"
          ) {{reaction.dataset_id}}
</template>

<style lang="sass" scoped>
@use '@/styles/vars' as *
.reaction-container
  text-decoration: none
  .row
    background-color: white
    border-radius: 0.25rem
    padding: 0.75rem
    margin-bottom: 1rem
    transition: 0.25s
    border: 4px solid white
    &:hover
      box-shadow: 0 0 5px $color-shadow-2
    .select
      input, label
        cursor: pointer
    .reaction-table
      color: black
      overflow-x: wrap
    .is-mined
      display: flex
      flex-direction: row-reverse
    .is-mined-badge
      text-align: center
      border-radius: 5px
      background-color: $color-primary
      color: $color-background-white
      font-size: 0.8rem
      width: 60px
    .info
      display: grid
      grid-template-columns: repeat(2, 50%)
      row-gap: 0.5rem
      column-gap: 1rem
      margin-top: 1rem
      .col.full
        grid-column: 1/3
        button
          font-size: 1.2rem
      .col
        *
          margin-top: 0.5rem
      .smile
        display: flex
        column-gap: 0.5rem
        align-items: center
        margin-top: 0.25rem
        .value
          width: 100%
          white-space: nowrap
          overflow: hidden
          text-overflow: ellipsis
    &.selected
      border-color: $color-primary
</style>

// app/src/components/ReactionCard.tsx
/**
 * Copyright 2023 Open Reaction Database Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import reaction_pb from 'ord-schema';
import type { CompoundIdentifier, ProductMeasurement } from 'ord-schema/proto/reaction_pb';
import LoadingSpinner from './LoadingSpinner';
import CopyButton from './CopyButton';
import { enumName } from '../utils/enum';
import { formatPercentage } from '../utils/outcomes';
import type { SearchResult, ReactionData } from '../types/search';
import './ReactionCard.scss';

interface ReactionCardProps {
  reaction: SearchResult & { dataset_id?: string };
  isSelectable?: boolean;
  isSelected?: boolean;
  onSelectionChange?: (reactionId: string, isSelected: boolean) => void;
}

const YIELD_MEASUREMENT_TYPE = 3; // ord-schema ProductMeasurementType.YIELD

const ReactionCard: React.FC<ReactionCardProps> = ({
  reaction,
  isSelectable = true,
  isSelected = false,
  onSelectionChange,
}) => {
  const navigate = useNavigate();
  const [reactionTable, setReactionTable] = useState<string | null>(null);

  const getReactionTable = useCallback(async () => {
    try {
      const response = await fetch(`/api/reaction_summary?reaction_id=${reaction.reaction_id}`);
      const responseData = await response.text();
      setReactionTable(responseData);
    } catch (error) {
      console.error('Error fetching reaction table:', error);
    }
  }, [reaction.reaction_id]);

  const getYield = (measurements: ProductMeasurement.AsObject[] = []): string => {
    const yieldObj = measurements.find(m => m.type === YIELD_MEASUREMENT_TYPE);
    return yieldObj?.percentage ? formatPercentage(yieldObj.percentage) : 'Not listed';
  };

  const getConversion = (data: ReactionData | undefined): string => {
    const conversion = data?.outcomesList?.[0]?.conversion;
    if (!conversion) return 'Not listed';
    return formatPercentage(conversion);
  };

  const conditionsAndDuration = (data: ReactionData | undefined): string[] => {
    const details: string[] = [];
    if (!data) return details;

    const temp = data.conditions?.temperature?.setpoint;
    if (temp) {
      const units = enumName(reaction_pb.Temperature.TemperatureUnit, temp.units);
      details.push(`at ${temp.value}${units ? ` ${units.toLowerCase()}` : '°C'}`);
    }

    const pressure = data.conditions?.pressure?.setpoint;
    if (pressure) {
      const units = enumName(reaction_pb.Pressure.PressureUnit, pressure.units);
      details.push(`under ${pressure.value}${units ? ` ${units.toLowerCase()}` : ' atm'}`);
    }

    const reactionTime = data.outcomesList?.[0]?.reactionTime;
    if (reactionTime?.value) {
      const units = enumName(reaction_pb.Time.TimeUnit, reactionTime.units);
      details.push(`for ${reactionTime.value}${units ? ` ${units.toLowerCase()}` : 's'}`);
    }

    return details;
  };

  const productIdentifier = (identifier: CompoundIdentifier.AsObject): string => {
    const type = enumName(reaction_pb.CompoundIdentifier.CompoundIdentifierType, identifier.type);
    return `${type ?? ''}: ${identifier.value}`;
  };

  const handleCheckboxChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (onSelectionChange) {
      onSelectionChange(reaction.reaction_id, event.target.checked);
    }
  };

  const handleViewDetails = () => {
    navigate(`/id/${reaction.reaction_id}`);
  };

  useEffect(() => {
    getReactionTable();
  }, [getReactionTable]);

  const reactionData = reaction.data;
  const firstOutcome = reactionData?.outcomesList?.[0];
  const firstProduct = firstOutcome?.productsList?.[0];
  const firstProductIdentifier = firstProduct?.identifiersList?.[0];
  const provenance = reactionData?.provenance;

  return (
    <div className="reaction-container">
      <div className={`row ${isSelected ? 'selected' : ''}`}>
        {isSelectable && (
          <div className="select">
            <input
              type="checkbox"
              id={`select_${reaction.reaction_id}`}
              value={reaction.reaction_id}
              checked={isSelected}
              onChange={handleCheckboxChange}
            />
            <label htmlFor={`select_${reaction.reaction_id}`}>Select reaction</label>
          </div>
        )}

        {provenance?.isMined && (
          <div className="is-mined">
            <div className="is-mined-badge">Mined</div>
          </div>
        )}

        <div className="reaction-table">
          {reactionTable ? <div dangerouslySetInnerHTML={{ __html: reactionTable }} /> : <LoadingSpinner />}
        </div>

        <div className="info">
          <div className="col full">
            <button onClick={handleViewDetails}>View Full Details</button>
          </div>

          <div className="col">
            <div className="yield">Yield: {getYield(firstProduct?.measurementsList || [])}</div>
            <div className="conversion">Conversion: {getConversion(reactionData)}</div>
            <div className="conditions">
              Conditions: {conditionsAndDuration(reactionData).join('; ') || 'Not Listed'}
            </div>
            {firstProductIdentifier && (
              <div className="smile">
                <CopyButton textToCopy={firstProductIdentifier.value || ''} />
                <div className="value">Product {productIdentifier(firstProductIdentifier)}</div>
              </div>
            )}
          </div>

          <div className="col">
            <div className="creator">
              Uploaded by {provenance?.recordCreated?.person?.name || 'Unknown'},{' '}
              {provenance?.recordCreated?.person?.organization || 'Unknown'}
            </div>
            <div className="date">
              Uploaded on{' '}
              {provenance?.recordCreated?.time?.value
                ? new Date(provenance.recordCreated.time.value).toLocaleDateString()
                : 'Unknown'}
            </div>
            <div className="doi">DOI: {provenance?.doi || 'Not available'}</div>
            {provenance?.publicationUrl && (
              <div className="publication">
                <a
                  href={provenance.publicationUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Publication URL
                </a>
              </div>
            )}
            <div className="dataset">
              Dataset:{' '}
              <a
                href={`/search?dataset_id=${reaction.dataset_id}&limit=100`}
                target="_blank"
                rel="noopener noreferrer"
              >
                {reaction.dataset_id}
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReactionCard;
