// app/src/views/search/SearchResults.vue
<script>
import EntityTable from '@/components/EntityTable'
import LoadingSpinner from '@/components/LoadingSpinner'
import ReactionCard from '@/components/ReactionCard'
import CopyButton from '@/components/CopyButton'
import DownloadResults from '@/components/DownloadResults'

export default {
  props: {
    searchResults: Array,
  },
  components: {
    EntityTable,
    LoadingSpinner,
    CopyButton,
    ReactionCard,
    DownloadResults,
  },
  data() {
    return {
      formattedResults: [],
      selectedReactions: [],
      showDownloadResults: false,
    }
  },
  computed: {
    fullUrl() {
      return window.location.href
    }
  },
  methods: {
    updateSelectedReactions(event) {
      if (event.target.checked) {
        this.selectedReactions.push(event.target.value)
      } else {
        let idx = this.selectedReactions.indexOf(event.target.value)
        if (idx !== -1) {
          this.selectedReactions.splice(idx, 1)
        }
      }
    },
    goToViewSelected() {
      // store storedSet in vuex so we can retrieve it if user comes back from selected-set
      this.$store.commit('setStoredSet', { query: window.location.search, reactions: this.selectedReactions})
      this.$router.push({ name: 'selected-set', query: {reaction_ids: this.selectedReactions}})
    }
  },
  async mounted() {
    this.formattedResults = this.searchResults
    // if query matches storedSet, set selectedReactions
    if (window.location.search == this.$store.state.storedSet?.query) {
      this.selectedReactions = this.$store.state.storedSet.reactions
    }
  },
}
</script>

<template lang="pug">
.search-results-main
  EntityTable(
    :tableData='formattedResults'
    title="Search Results",
    v-slot='{ entities }'
    v-if='formattedResults.length'
    :displaySearch='false'
  ) 
    .action-button-holder
      CopyButton(
        :textToCopy='fullUrl'
        icon='share'
        buttonText='Shareable Link'
      )
      button(
        :disabled='!formattedResults.length'
        @click='showDownloadResults=true'
      ) Download All Search Results
    ReactionCard(
      v-for='row in entities'
      :reaction='row'
      :isSelectable='true'
      :isSelected='selectedReactions.includes(row.reaction_id)'
      @clickedSelect='updateSelectedReactions'
    )
  transition(
    name='fade'
  )
    .view-selected-container(v-if='selectedReactions.length')
      .view-selected-button(@click='goToViewSelected') View {{selectedReactions.length}} selected reactions
  DownloadResults(
    :reactionIds='formattedResults.map(result => result.reaction_id)'
    :showDownloadResults='showDownloadResults'
    @hideDownloadResults='showDownloadResults=false'
  )
</template>

<style lang="sass" scoped>
@import '@/styles/vars.sass'
@import '@/styles/transition.sass'
.search-results-main
  .action-button-holder
    margin: -2.5rem 0 1rem // bring button row inline with title without having to pass too much into EntityTable
    display: flex
    justify-content: flex-end
    column-gap: 0.5rem
    button
  .reaction-container
    text-decoration: none
    .row
      background-color: white
      border-radius: 0.25rem
      padding: 0.75rem
      margin-bottom: 1rem
      transition: 0.25s
      border: 4px solid white
      &:hover
        box-shadow: 0 0 5px $darkgrey
      .select
        input, label
          cursor: pointer
      .reaction-table
        color: black
        overflow-x: wrap
      .info
        display: grid
        grid-template-columns: repeat(2, 50%)
        row-gap: 0.5rem
        column-gap: 1rem
        margin-top: 1rem
        .col.full
          grid-column: 1/3
          button
            font-size: 1.2rem
        .col
          *
            margin-top: 0.5rem
        .smile
          display: flex
          column-gap: 0.5rem
          align-items: center
          margin-top: 0.25rem
          .value
            width: 100%
            white-space: nowrap
            overflow: hidden
            text-overflow: ellipsis
      &.selected
        border-color: $linkblue
  .view-selected-container
    position: fixed
    bottom: 2rem
    right: 6.5rem
    .view-selected-button
      padding: 0.5rem 1rem
      color: white
      background-color: $linkblue
      border-radius: 0.25rem
      cursor: pointer
      box-shadow: 0 0 5px $darkgrey
      animation: bounce 5s infinite ease-in-out
      @keyframes bounce
        0%, 20%
          transform: translateY(0)
        10%
          transform: translateY(-10px)
  @media (max-width: 1000px)
    margin-top: 2.5rem

</style>

// app/src/components/SearchResults.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import EntityTable from './EntityTable';
import ReactionCard from './ReactionCard';
import CopyButton from './CopyButton';
import DownloadResults from './DownloadResults';
import './SearchResults.scss';

interface SearchResult {
  reaction_id: string;
  [key: string]: any;
}

interface SearchResultsProps {
  searchResults: SearchResult[];
  isOverflow: boolean;
}

const SearchResults: React.FC<SearchResultsProps> = ({
  searchResults,
  isOverflow
}) => {
  const navigate = useNavigate();
  const [formattedResults, setFormattedResults] = useState<SearchResult[]>([]);
  const [selectedReactions, setSelectedReactions] = useState<string[]>([]);
  const [showDownloadResults, setShowDownloadResults] = useState(false);

  const updateSelectedReactions = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value;
    const checked = event.target.checked;

    if (checked) {
      setSelectedReactions(prev => [...prev, value]);
    } else {
      setSelectedReactions(prev => prev.filter(id => id !== value));
    }
  };

  const goToViewSelected = () => {
    // Store selected reactions in sessionStorage for navigation
    sessionStorage.setItem('selectedReactions', JSON.stringify({
      query: window.location.search,
      reactions: selectedReactions
    }));
    
    navigate(`/selected-set?reaction_ids=${selectedReactions.join(',')}`);
  };

  useEffect(() => {
    setFormattedResults(searchResults);
    
    // Check if there are stored selected reactions for this query
    const stored = sessionStorage.getItem('selectedReactions');
    if (stored) {
      const { query, reactions } = JSON.parse(stored);
      if (query === window.location.search) {
        setSelectedReactions(reactions);
      }
    }
  }, [searchResults]);

  const title = isOverflow 
    ? "100 Reactions From This Dataset (Sample)" 
    : `Reactions in this Dataset (${formattedResults.length} Reactions)`;

  return (
    <div className="search-results">
      {formattedResults.length > 0 && (
        <EntityTable
          tableData={formattedResults}
          title={title}
          displaySearch={false}
        >
          {(entities) => (
            <>
              <div className="search-results__action-buttons">
                <CopyButton
                  textToCopy={window.location.href}
                  icon="share"
                  buttonText="Shareable Link"
                />
                <button
                  disabled={!formattedResults.length}
                  onClick={() => setShowDownloadResults(true)}
                >
                  Download All Search Results
                </button>
              </div>
              
              {entities.map((row: SearchResult) => (
                <div key={row.reaction_id} className="search-results__reaction-wrapper">
                  <input
                    type="checkbox"
                    value={row.reaction_id}
                    checked={selectedReactions.includes(row.reaction_id)}
                    onChange={updateSelectedReactions}
                    className="search-results__checkbox"
                  />
                  <ReactionCard
                    reaction={row}
                    isSelectable={false}
                    isSelected={selectedReactions.includes(row.reaction_id)}
                  />
                </div>
              ))}
            </>
          )}
        </EntityTable>
      )}

      {selectedReactions.length > 0 && (
        <div className="search-results__view-selected">
          <div 
            className="search-results__view-selected-button"
            onClick={goToViewSelected}
          >
            View {selectedReactions.length} selected reactions
          </div>
        </div>
      )}

      <DownloadResults
        reactionIds={formattedResults.map(result => result.reaction_id)}
        showDownloadResults={showDownloadResults}
        onHideDownloadResults={() => setShowDownloadResults(false)}
      />
    </div>
  );
};

export default SearchResults;
