// app/src/views/reaction-view/ConditionsView.vue
<!--
 Copyright 2023 Open Reaction Database Project Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<script>
import reaction_pb from "ord-schema"
import conditionUtil from "@/utils/conditions"

export default {
  props: {
    conditions: Object,
    display: String,
  },
  computed: {
    tempType () {
      return conditionUtil.tempType(this.conditions.temperature.control?.type)
    },
    tempSetPoint () {
      return conditionUtil.tempSetPoint(this.conditions.temperature?.setpoint)
    },
    pressureType () {
      return conditionUtil.pressureType(this.conditions.pressure.control?.type)
    },
    pressureSetPoint () {
      return conditionUtil.pressureSetPoint(this.conditions.pressure?.setpoint)
    },
    pressureAtmo () {
      return conditionUtil.pressureAtmo(this.conditions.pressure?.atmosphere)
    },
    stirType () {
      return conditionUtil.stirType(this.conditions.stirring?.type)
    },
    stirRate () {
      return conditionUtil.stirRate(this.conditions.stirring?.rate)
    },
    stirRate () {
      return conditionUtil.stirRate(this.conditions.stirring.rate)
    },
    illumType () {
      return conditionUtil.illumType(this.conditions.illumination)
    },
    elecChemType () {
      return conditionUtil.elecChemType(this.conditions.electrochemistry)
    },
    elecChemCurrent () {
      return conditionUtil.elecChemCurrent(this.conditions.electrochemistry)
    },
    elecChemCellType () {
      return conditionUtil.elecChemCellType(this.conditions.electrochemistry)
    }
  },
  mounted () {
    console.log('reaction_pb',reaction_pb)
  }
}
</script>

<template lang="pug">
.conditions-view
  .temperature.details(v-if='display==="temperature"')
    .label Control Type
    .value {{tempType}}
    template(v-if='conditions.temperature.control?.details')
      .label Details
      .value {{conditions.temperature.control.details}}
    .label Setpoint
    .value {{tempSetPoint}}
    // TODO Flesh out temp measurements
    template(v-if='conditions.temperature.measurementsList?.length')
      .label Measurements
      .value {{conditions.temperature.measurementsList}}
    
  .pressure.details(v-if='display==="pressure"')
    .label Control Type
    .value {{pressureType}}
    template(v-if='conditions.pressure.control.details')
      .label Details
      .value {{conditions.pressure.control.details}}
    .label Setpoint
    .value {{pressureSetPoint}}
    .label Atmosphere
    .value {{pressureAtmo}}
    // TODO Flesh out pressure measurements
    template(v-if='conditions.pressure.measurementsList?.length')
      .label Measurements
      .value {{conditions.pressure.measurementsList}}

  .stirring.details(v-if='display==="stirring"')
    .label Type
    .value {{stirType}}
    template(v-if='conditions.stirring.details')
      .label Details
      .value {{conditions.stirring.details}}
    .label Rate
    .value {{stirRate || "UNSPECIFIED"}}
    template(v-if='conditions.stirring.rate?.rpm')
      .label RPM
      .value {{conditions.stirring.rate.rpm}}

  .illumination.details(v-if='display==="illumination"')
    .label Type
    .value {{illumType}}
    // TODO flesh out wave length
    .label Peak Wavelength
    .value {{conditions.illumination.peakWaveLength || "None"}}
    template(v-if='conditions.illumination.color')
      .label Color
      .value {{conditions.illumination.color}}
    // TODO flesh out distance
    .label Distance to Vessel
    .value {{conditions.illumination.distanceToVessel || "None"}}

  .electro.details(v-if='display === "electrochemistry"')
    .label Type
    .value {{elecChemType}}
    .label Details
    .value {{conditions.electrochemistry.details}}
    .label Current
    .value {{elecChemCurrent}}
    .label Anode
    .value {{conditions.electrochemistry.anodeMaterial}}
    .label Cathode
    .value {{conditions.electrochemistry.cathodeMaterial}}
    template(v-if='conditions.electrochemistry.cell')
      .label Cell Type
      .value {{elecChemCellType}}
      .label Cell Details
      .value {{conditions.electrochemistry.cell.details}}
    .label raw
  
  // TODO flesh out flow
  .electro.details(v-if='display === "flow"')
    .label Type
    .value {{conditions.flow}}

  // TODO flesh out other
  .other.details(v-if='display === "other"')
    template(v-if='conditions.reflux')
      .label Reflux
      .value {{conditions.reflux}}
    template(v-if='conditions.ph')
      .label pH
      .value {{conditions.ph}}
    template(v-if='conditions.conditions_are_dynamic')
      .label Conditions are dynamic
      .value {{conditions.conditions_are_dynamic}}
    template(v-if='conditions.details')
      .label Details
      .value {{conditions.details}}
</template>

<style lang="sass" scoped>
.conditions-view
  .details
    display: grid
    grid-template-columns: auto 1fr
    column-gap: 1rem
    row-gap: 0.5rem
</style>

// app/src/views/reaction-view/ConditionsView.tsx
/**
 * Copyright 2023 Open Reaction Database Project Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import {
  illumType,
  lengthStr,
  pressureAtmo,
  pressureSetPoint,
  pressureType,
  stirRate,
  stirType,
  tempSetPoint,
  tempType,
} from '../../utils/conditions';
import type { ReactionConditionsData } from '../../types/search';
import './ConditionsView.scss';

interface ConditionsViewProps {
  conditions: ReactionConditionsData | undefined;
  display: string;
}

const ConditionsView: React.FC<ConditionsViewProps> = ({ conditions, display }) => {
  if (!conditions) return null;

  if (display === 'temperature') {
    const t = conditions.temperature;
    return (
      <div className="conditions-view">
        <div className="temperature details">
          <div className="label">Control Type</div>
          <div className="value">{tempType(t?.control?.type)}</div>
          {t?.control?.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{t.control.details}</div>
            </>
          )}
          <div className="label">Setpoint</div>
          <div className="value">{tempSetPoint(t?.setpoint)}</div>
          {t?.measurementsList && t.measurementsList.length > 0 && (
            <>
              <div className="label">Measurements</div>
              {/* TODO: render temperature measurements once the schema's shape is fully ported. */}
              <div className="value">{t.measurementsList.length} recorded</div>
            </>
          )}
        </div>
      </div>
    );
  }

  if (display === 'pressure') {
    const p = conditions.pressure;
    return (
      <div className="conditions-view">
        <div className="pressure details">
          <div className="label">Control Type</div>
          <div className="value">{pressureType(p?.control?.type)}</div>
          {p?.control?.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{p.control.details}</div>
            </>
          )}
          <div className="label">Setpoint</div>
          <div className="value">{pressureSetPoint(p?.setpoint)}</div>
          <div className="label">Atmosphere</div>
          <div className="value">{pressureAtmo(p?.atmosphere)}</div>
          {p?.measurementsList && p.measurementsList.length > 0 && (
            <>
              <div className="label">Measurements</div>
              {/* TODO: render pressure measurements once the schema's shape is fully ported. */}
              <div className="value">{p.measurementsList.length} recorded</div>
            </>
          )}
        </div>
      </div>
    );
  }

  if (display === 'stirring') {
    const s = conditions.stirring;
    return (
      <div className="conditions-view">
        <div className="stirring details">
          <div className="label">Type</div>
          <div className="value">{stirType(s?.type)}</div>
          {s?.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{s.details}</div>
            </>
          )}
          <div className="label">Rate</div>
          <div className="value">{stirRate(s?.rate) || 'UNSPECIFIED'}</div>
          {s?.rate?.rpm !== undefined && s.rate.rpm !== 0 && (
            <>
              <div className="label">RPM</div>
              <div className="value">{s.rate.rpm}</div>
            </>
          )}
        </div>
      </div>
    );
  }

  if (display === 'illumination') {
    const i = conditions.illumination;
    const distance = lengthStr(i?.distanceToVessel);
    return (
      <div className="conditions-view">
        <div className="illumination details">
          <div className="label">Type</div>
          <div className="value">{illumType(i)}</div>
          <div className="label">Peak Wavelength</div>
          <div className="value">{lengthStr(i?.peakWavelength) ?? 'None'}</div>
          {i?.color && (
            <>
              <div className="label">Color</div>
              <div className="value">{i.color}</div>
            </>
          )}
          <div className="label">Distance to Vessel</div>
          <div className="value">{distance ?? 'None'}</div>
        </div>
      </div>
    );
  }

  if (display === 'electrochemistry') {
    const e = conditions.electrochemistry;
    return (
      <div className="conditions-view">
        <div className="electro details">
          <div className="label">Type</div>
          <div className="value">{String(e?.type ?? '')}</div>
          {e?.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{e.details}</div>
            </>
          )}
          {e?.anodeMaterial && (
            <>
              <div className="label">Anode</div>
              <div className="value">{e.anodeMaterial}</div>
            </>
          )}
          {e?.cathodeMaterial && (
            <>
              <div className="label">Cathode</div>
              <div className="value">{e.cathodeMaterial}</div>
            </>
          )}
          {/* TODO: render current, voltage, electrodeSeparation, and measurementsList. */}
        </div>
      </div>
    );
  }

  if (display === 'flow') {
    const f = conditions.flow;
    return (
      <div className="conditions-view">
        <div className="electro details">
          <div className="label">Type</div>
          <div className="value">{String(f?.type ?? '')}</div>
          {f?.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{f.details}</div>
            </>
          )}
          {f?.pumpType && (
            <>
              <div className="label">Pump Type</div>
              <div className="value">{f.pumpType}</div>
            </>
          )}
          {/* TODO: render tubing dimensions if/when needed. */}
        </div>
      </div>
    );
  }

  if (display === 'other') {
    return (
      <div className="conditions-view">
        <div className="other details">
          {conditions.reflux && (
            <>
              <div className="label">Reflux</div>
              <div className="value">yes</div>
            </>
          )}
          {conditions.ph !== undefined && conditions.ph !== 0 && (
            <>
              <div className="label">pH</div>
              <div className="value">{conditions.ph}</div>
            </>
          )}
          {conditions.conditionsAreDynamic && (
            <>
              <div className="label">Conditions are dynamic</div>
              <div className="value">yes</div>
            </>
          )}
          {conditions.details && (
            <>
              <div className="label">Details</div>
              <div className="value">{conditions.details}</div>
            </>
          )}
        </div>
      </div>
    );
  }

  return null;
};

export default ConditionsView;
